# Generated by Django 3.2.6 on 2021-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='duracion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='espiracion',
            field=models.DateTimeField(null=True),
        ),
    ]
