# Generated by Django 3.2.6 on 2021-09-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210831_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
